name: test_deploy_UIB_AWS
on:
  workflow_dispatch:
    inputs:
      bonita_dns_name:
        description: 'Bonita server DNS name'
        required: true
        type: string

jobs:
  deploy_UIB_AWS:
    uses: ./.github/workflows/reusable_deploy_uib_aws.yml
    with:
      bonita_dns_name: ${{ inputs.bonita_dns_name }}
      uib_folder: uib
    secrets: inherit

