name: test_get_bonita_logs
on:
  workflow_dispatch:
jobs:
  env:
    bonita_dns_name: "bonita_dns_name"
  get_bonita_logs:
    uses: ./.github/workflows/reusable_get_bonita_logs.yml
    with:
      bonita_dns_name: ${{ env.bonita_dns_name }}
      bonita_service: 'bonita'
    secrets: inherit

  get_bonita_ui_logs:
    uses: ./.github/workflows/reusable_get_bonita_logs.yml
    with:
      bonita_dns_name: ${{ env.bonita_dns_name }}
      bonita_service: 'bonita_ui'
    secrets: inherit

  get_bonita_ui_proxy_logs:
      uses: ./.github/workflows/reusable_get_bonita_logs.yml
      with:
        bonita_dns_name: ${{ env.bonita_dns_name }}
        bonita_service: 'bonita_ui_proxy'
      secrets: inherit